# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https

# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: !!null code

# Aliases allow you to create nicknames for gh commands
aliases:

hosts:
    github.com:
        oauth_token: TOKEN
        user: USER
